### PR TITLE
ensure consistent order of templates - closes #99

### LINKED ISSUE #99: output differs across multiple executions against the same source
Templates are not returned by walkdir in a consistent order.  This is causing our later minification/hash build step to yield different outputs from the same source.

### PR DESCRIPTION
**Pull request by spanditcaa**
This was expedient, but may not be the most efficient way to solve the problem discussed in #99.

### CODE REVIEW

**Comment by lukekarrys** [comment]
The type of solution looks good to me (sorting files to ensure consistency) but tests are no longer passing for me on travis or locally. I'd be happy to merge if you can get them passing again.

**Comment by spanditcaa** [comment]
They didn't pass for me before I started :(  I'll try to check it out when I have some time..

**Comment by spanditcaa** [comment]
My prior test fail may have been a windows thing.  Fixed a bug and now passing from local mac and travis @lukekarrys.

**Comment by lukekarrys** [comment]
Thanks @spanditcaa! Published as `v2.0.5`

**Pull request merged**
