### PR TITLE
Skip files not matching the initial globbing pattern

### PR DESCRIPTION
**Pull request by jblanche**

### CODE REVIEW

**Comment by lukekarrys** [comment]
Thanks for the PR @jblanche! This is to fix #79 right (which I agree should be fixed)?

It looks the `indexOf` check is breaking some existing tests, is there anyway you could look into that and see if these is a different check that could be done there instead? 

If not, hopefully I can take a look pretty soon.

**Comment by jblanche** [comment]
Hi, yes it supposed to fix this issue but I didn't managed to pass the tests, the errors I had didn't look related so I tried to push anyway, looks like I should have investigate a bit more :) 
I'll see if I can spend some time on it next week.

**Comment by jblanche** [comment]
I tried to give a better look at the tests but I didn't succeed to make them pass in any version of Templatizer. 
I get an empty `templatizer` object on https://github.com/HenrikJoreteg/templatizer/blob/master/test/tests.js#L20 and a bunch of other errors :(

**Comment by lukekarrys** [comment]
Thanks for the effort @jblanche. The testing setup is pretty confusing unfortunately :( I will take a look this week so I can this sorted out and the bug fixed. Thanks again for taking a look!

**Comment by lukekarrys** [comment]
Closing in favor of #82.

**Pull request closed without merging**
